# Site settings

title: Just sudo IT
email: ka1130@o2.pl
description: > # this means to ignore newlines until "baseurl:"
  Dev lines from a coding novice toiling to become a ninja.
baseurl: ""
url: "http://just-sudo-it.pl"
twitter_username: ka1130
github_username:  ka1130

enable_retina: false
permalink: :title
nav_list:
  Home : ['Home', '/', 'fa-home']
  #Home_Alt : ['Home Alt', '/home-alt', 'fa-home']
  #Home_Alt_2 : ['Home Alt 2', '/home-alt-2/', 'fa-home']
  About : ['About', '/about', 'fa-anchor']
  Contact : ['Contact', '/contact', 'fa-plane']
  Author : ['Author', '/author/kamila', 'fa-user']
single_footer: '<p> Kamila Matla-Tomczyk &copy; 2017 <a href="/">latest posts</a></p>'
footer_links:
    About: ['About', '/about']
    Kamila Matla-Tomczyk: ['&copy; 2017 Kamila Matla-Tomczyk', 'author/kamila']

# Build settings
#markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
